accounts/urls.py
from django.urls import path
from accounts.views import login_user, edit_user, logout, RegisterUser

app_name = 'accounts'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('edit/', edit_user, name='edit'),
    path('logout/', logout, name='logout'),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp
from rest_framework.routers import DefaultRouter
from catalog.api import CatalogViewSet, ProductViewSet


router = DefaultRouter()
router.register('categories', CatalogViewSet)
router.register('products', ProductViewSet)

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('admin/', admin.site.urls, name='admin'),
    path('api/', include(router.urls)),
    path('', include('catalog.urls')),
    path('', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

# Create your models here.

class Account(AbstractUser):
    avatar = models.ForeignKey(
        'images.Image',
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    phone = models.CharField(
        max_length=12,
        blank=True,
        null=True
    )

    age = models.PositiveIntegerField(
        verbose_name='Возраст',
        blank=True,
        null=True
    )

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from accounts.models import Account


class LoginForm(AuthenticationForm):
    class Meta:
        model = Account
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class RegisterForm(UserCreationForm):
    class Meta:
        model = Account
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'age', 'avatar', 'phone')

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data and data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data


class UserEditForm(UserChangeForm):
    class Meta:
        model = Account
        fields = ('password', 'first_name', 'last_name', 'email', 'age', 'avatar')
    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
               field.widget = forms.PasswordInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import auth
from accounts.forms import LoginForm, RegisterForm, UserEditForm
from accounts.models import Account
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView


def login_user(request):
    title = 'Вход'
    success_url = 'catalog:catalog'
    login_form = LoginForm(data=request.POST)
    if request.method == 'POST':
        user = request.POST.get('username')
        passwd = request.POST.get('password')
        auth_user = auth.authenticate(username=user, password=passwd)

        if auth_user and auth_user.is_active:
            auth.login(request, auth_user)
            return redirect(success_url)

    content = {'title': title, 'login_form': login_form}

    return render(request, 'accounts/login.html', content)


class RegisterUser(CreateView):
    model = Account
    template_name = 'accounts/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('accounts:login')


@login_required(login_url=reverse_lazy('accounts:login'))
def edit_user(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            success_url = reverse_lazy('accounts:login')
            return redirect(success_url)
    else:
        edit_form = UserEditForm(instance=request.user)

    content = {'title': title, 'edit_form': edit_form}

    return render(request, 'accounts/edit.html', content)


@login_required(login_url=reverse_lazy('accounts:login'))
def logout(request):
    auth.logout(request)
    success_url = reverse_lazy('accounts:login')
    return redirect(success_url)

accounts/templates/accounts/edit.html
{% extends 'server/master.html' %}

<title>
    {% block page_title %}
        {{ title|title }}
    {% endblock %}
</title>


<div class="content">
    {% block page_content %}
        <form action="{% url 'accounts:edit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Username: {{ user|title }}</p>
            {{ edit_form.as_p }}
            <input class="form-control" type="submit" , value="Submit">
        </form>
    {% endblock %}
</div>

accounts/templates/accounts/login.html
{% extends 'server/master.html' %}

<title>
    {% block page_title %}
        {{ title|title }}
    {% endblock %}
</title>


<div class="content">
    {% block page_content %}
        <h3 class="prod_name">{{ user }}</h3>
        <form action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            {{ login_form.as_p }}
            <input class="form-control" type="submit" , value="Submit">
        </form>
    {% endblock %}
</div>

accounts/templates/accounts/register.html
{% extends 'server/master.html' %}

<title>
    {% block page_title %}
        {{ title|title }}
    {% endblock %}
</title>


<div class="content">
    {% block page_content %}
        <form action="{% url 'accounts:register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" , value="Submit">
        </form>
    {% endblock %}
</div>