catalog/urls.py
from django.urls import path
from catalog.views import (
    CatalogView, ProductDeleteView, ProductUpdateView,
    ProductDetailView, ProductCreateView
    )

from catalog.views import (
    CatalogView, ProductDeleteView, ProductUpdateView,
    ProductDetailView, ProductCreateView, CategoryView
    )

app_name = 'catalog'


urlpatterns = [
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('catalog/category/<int:pk>/', CategoryView.as_view(), name='category'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('catalog/update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('catalog/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('catalog/detail/<int:pk>/', ProductDetailView.as_view(), name='detail'),

]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp
from rest_framework.routers import DefaultRouter
from catalog.api import CatalogViewSet, ProductViewSet


router = DefaultRouter()
router.register('categories', CatalogViewSet)
router.register('products', ProductViewSet)

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('admin/', admin.site.urls, name='admin'),
    path('api/', include(router.urls)),
    path('', include('catalog.urls')),
    path('', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


# Create your models here.

class CatalogCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True
    )

    modified = models.DateTimeField(
        auto_now=True
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return self.name


class ProductDetail(models.Model):
    category = models.ForeignKey(
        CatalogCategory,
        on_delete=models.CASCADE
    )
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=255,
        unique=True
    )
    image = models.ForeignKey(
        'images.Image',
        on_delete=models.PROTECT
    )
    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=100,
        blank=True,
        null=True
    )
    spec = models.TextField(
        verbose_name='характеристики',
        blank=True
    )
    description = models.TextField(
        verbose_name='подробное описание',
        blank=True, null=True
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0
    )
    quantity = models.PositiveIntegerField(
        verbose_name='склад',
        default=0
    )
    modified = models.DateTimeField(
        auto_now=True
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return ' '.join((self.name, self.category.name))

catalog/forms.py
from django import forms
from catalog.models import CatalogCategory, ProductDetail



class CategoryForm(forms.ModelForm):
    class Meta:
        model = CatalogCategory
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'default_form'



class ProductForm(forms.ModelForm):
    class Meta:
        model = ProductDetail
        fields = (
            'name',
            'category',
            'image',
            'description',
            'short_desc',
            'spec',
            'price',
            'quantity'
        )

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'default_form'

catalog/views/category.py
from django.views.generic import (
    ListView, CreateView, UpdateView,
    DeleteView
)

from django.urls import reverse_lazy

from catalog.forms import CategoryForm
from catalog.models import ProductDetail, CatalogCategory
from accounts.mixins import AdminGroupRequired
from django.contrib.auth.mixins import LoginRequiredMixin



class CatalogView(ListView):
    model = ProductDetail
    queryset = CatalogCategory.objects.all()
    template_name = 'catalog/catalog.html'
    context_object_name = 'results'
    paginate_by = 3


class CategoryView(ListView):
    model = ProductDetail
    template_name = 'catalog/category.html'
    context_object_name = 'results'
    paginate_by = 3

    def get_queryset(self, **kwargs):
        return ProductDetail.objects.filter(
            category_id=self.kwargs['pk']
        )


class CategoryCreateView(LoginRequiredMixin, AdminGroupRequired, CreateView):
    model = CatalogCategory
    template_name = 'catalog/create.html'
    form_class = CategoryForm
    success_url = reverse_lazy('catalog:catalog')
    redirect_url = success_url


class CategoryUpdateView(LoginRequiredMixin, AdminGroupRequired, UpdateView):
    model = CatalogCategory
    template_name = 'catalog/create.html'
    form_class = CategoryForm
    success_url = reverse_lazy('catalog:catalog')
    redirect_url = success_url


class CategoryDeleteView(LoginRequiredMixin, AdminGroupRequired, DeleteView):
    model = CatalogCategory
    template_name = 'catalog/delete.html'
    success_url = reverse_lazy('catalog:catalog')
    redirect_url = success_url

catalog/views/products.py
from django.views.generic import (
    DetailView, CreateView,UpdateView,
    DeleteView
)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from catalog.forms import ProductForm
from catalog.models import ProductDetail
from accounts.mixins import AdminGroupRequired


class ProductDetailView(DetailView):
    model = ProductDetail
    template_name = 'catalog/detail.html'
    context_object_name = 'instance'


class ProductCreateView(LoginRequiredMixin, AdminGroupRequired, CreateView):
    model = ProductDetail
    template_name = 'catalog/create.html'
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')
    redirect_url = success_url
    login_url = reverse_lazy('accounts:login')


class ProductUpdateView(LoginRequiredMixin, AdminGroupRequired, UpdateView):
    model = ProductDetail
    template_name = 'catalog/create.html'
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')
    redirect_url = success_url
    login_url = reverse_lazy('accounts:login')


class ProductDeleteView(LoginRequiredMixin, AdminGroupRequired, DeleteView):
    model = ProductDetail
    template_name = 'catalog/delete.html'
    success_url = reverse_lazy('catalog:catalog')
    redirect_url = success_url
    login_url = reverse_lazy('accounts:login')

catalog/templates/catalog/catalog.html
{% extends 'server/master.html' %}

<title>
    {% block page_title %}
        {{ title|title }}
    {% endblock %}
</title>

<div class="content">
    {% block page_content %}
        <h3 class="prod_name">Категории Товаров</h3>
        <div class="catalog">
            {% for item in results %}
                {% include 'catalog/components/category.html' with category=item id=item.pk %}
            {% endfor %}
        </div>
    {% endblock %}
</div>

catalog/templates/catalog/category.html
{% extends 'server/master.html' %}

<title>
    {% block page_title %}
        {{ title|title }}
    {% endblock %}
</title>

<div class="content">
    {% block page_content %}
        <h3 class="prod_name">Каталог</h3>
        <div class="catalog">
            {% for item in results %}
                {% include 'catalog/components/product.html' with product=item id=item.pk %}
            {% endfor %}
        </div>
        <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="pagination__control_previous">
                <a
                        href="?page={{ page_obj.previous_page_number }}"
                        class="pagination__link"
                >
                    Previous
                </a>
            </li>
        {% endif %}
        {% if page_obj.has_next %}
            <li class="pagination__control_next">
                <a
                        href="?page={{ page_obj.next_page_number }}"
                        class="pagination__link"
                >
                    Next
                </a>
            </li>
        {% endif %}
    {% endblock %}
</div>

catalog/templates/catalog/create.html
{% extends 'server/master.html' %}

<title>
    {% block page_title %}
        {{ title|title }}
    {% endblock %}
</title>


<div class="content">
    {% block page_content %}
        <form class="default_form" action="{% url 'catalog:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button">Отправить</button>
            <button type="reset" class="button">Сбросить</button>
        </form>
    {% endblock %}
</div>

catalog/templates/catalog/delete.html
{% extends 'server/master.html' %}

<title>
    {% block page_title %}
        {{ title|title }}
    {% endblock %}
</title>


<div class="content">
    {% block page_content %}
        <form class="default_form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit" class="button">Удалить</button>
        </form>
    {% endblock %}
</div>

catalog/templates/catalog/detail.html
{% extends 'server/master.html' %}

{% load utility %}

<title>
    {% block page_title %}
        {{ instance.name }}
    {% endblock %}
</title>

<div class="content">
    {% block page_content %}
        <p class="prod_name">{{ instance.name }}
        <div class="prod_block"><a href={{ instance.image.value.url }} target="_blank"><img class="prod_img" src={{ instance.image.value.url }} alt="{{ instance.name }}"></a></div>
        <h3 class="headline">Описание товара</h3>
        <p class="mini_desc">{{ instance.short_desc }}</p>
        <button type="submit" class="buy_button">Купить</button>
        <p><b>Цена: </b>{{ instance.price }}&#8381;</p>
        <p><b>Наличие на складе: </b>{{ instance.quantity }}</p>
        <h3 class="headline clear">Характеристики товара</h3>
        <p>{{ instance.spec }}</p>
        <h3 class="headline">Подробное описание товара</h3>
        <p class="desc">{{ instance.description }}</p>
    {% endblock %}
</div>

catalog/templates/catalog/update.html
{% extends 'server/master.html' %}

<title>
    {% block page_title %}
        {{ title|title }}
    {% endblock %}
</title>


<div class="content">
    {% block page_content %}
        <form class="default_form" action="{% url 'catalog:update' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button">Отправить</button>
            <button type="reset" class="button">Сбросить</button>
        </form>
    {% endblock %}
</div>